### PR TITLE
moved ConfigLoopsHip to hip_net.go for modular hip loops

### PR DESCRIPTION
**Pull request by zycyc**

### CODE REVIEW

**Comment by zycyc** [comment]
turned out to work just fine after migration @rcoreilly . rebased and should be ready

**Comment by rcoreilly** [comment]
Looks good but probably better in the long run to also use a HipModConfig struct instead of the args -- then if we need to add something in the future it is easier, and the comments provide info to user about the meaning etc.

**Comment by rcoreilly** [comment]
also needs updated with merge.

**Review by rcoreilly — APPROVED** [review]
Looks good!

**Pull request merged**
