### PR TITLE
Get rid of malloc in Neuron hot loop

### PR DESCRIPTION
**Pull request by siboehm**
Problem: After the large refactor, we're now doing a lot of memory allocations in the hot loop of NeuronFun, creating a new randctr every time we call CycleNeuron. This costs time, and triggers a lot of calls to GC.

I don't know if you want to merge this PR, I'm not really sure why this new randcntr was introduced (seems to be related to GPU stuff). There may be a better way to solve this problem.

My solution: I moved the randctr allocation out of the hotloop. We now only allocate once per thread.

PS: As an aside, I wonder how you're dealing with this alloc & free on GPU.

image

### CODE REVIEW

**Comment by rcoreilly** [comment]
That is weird -- it is just 2 uint32's that are a local var in the calling context -- it should just be on the stack of that calling context, no?    In the GPU it is just a local var passed down the call stack and the GPU inlines everything so it is just a local var period.

Anyway, given the logic of the slrand thing, it has to be per-neuron -- cannot be global like that, so this is not a possible solution.  You should see a race condition incrementing the slrand counter in Context in this version -- would be good to see why you don't see that!

**Comment by siboehm** [comment]
I don't see an RC because I create one of these randctrs per goroutine, so it's local. No other goroutine can access it. Is there any other reason why it has to be per-Neuron?

I guess theoretically the Go compiler escape analysis could figure out that randctr will not persist after the call to Cycle Neuron. However, because we pass the pointer down like 6 functions deep, I assume the compiler gives up at some point and doesn't realize we don't store the pointer anywhere. So if escape analysis cannot determine that the variable definitely doesn't outlive the function call scope, you have to put it on the heap.

**Comment by siboehm** [comment]
In C++ it would've been put onto the stack and if you'd persisted the pointer somewhere, that'd be your problem.

**Comment by siboehm** [comment]
From convo with Randy: The reason it's per Neuron is because we want it to produce the same random numbers no matter if it runs on GPU or single-threaded CPU or multi-threaded CPU.

But instead of passing around this struct, we can just have an enum (constant at compile time) with one entry per function. Then the randomness will depend on the neuronIndex and on the Function, so will be reproducible without requiring state passing.

**Comment by siboehm** [comment]
@rcoreilly all systems go

**Review by rcoreilly — APPROVED** [review]
all good!

**Pull request merged**
