### PR TITLE
document stringer generation

### PR DESCRIPTION
**Pull request by garymm**

### CODE REVIEW

**Comment by rcoreilly** [comment]
what tool is doing the auto-formatting, and can it be configured?  I much prefer * for itemized lists, and also + for indented lists.  underbar is fine for italics..  similar to all other cases of auto-formatting, probably we need to standardize and use such a tool systematically.

**Comment by rcoreilly** [comment]
btw, I consume and write a lot of markdown in raw format so the difference between * and - as an itemize is visually significant in the raw form, even if they end of formatting the same on the web.

**Comment by rcoreilly** [comment]
I realize this is swimming upstream, but doublespace after period makes a lot of sense for the monospace fonts used in editors used to write markdown.. https://stevelosh.com/blog/2012/10/why-i-two-space/

**Comment by garymm** [comment]
Undid the auto-formatting.

**Pull request merged**
