### PR TITLE
Save the log file every epoch

### PR DESCRIPTION
**Pull request by etuleu**
I save the file every epoch because it's nice to see a plot while training.
I also added the number of units to the file so I can plot the different runs in different files.

Misc: I removed the space in the key because that breaks some CSV programs.

### CODE REVIEW

**Comment by rcoreilly** [comment]
If you change column names in one place you have to change them in the other..

**Comment by etuleu** [comment]
> If you change column names in one place you have to change them in the other..

I thought I changed them in both places.
Or do you mean we should create some constants?

**Comment by rcoreilly** [comment]
oops it didn't highlight just those changes so I missed it -- you're right!

**Comment by etuleu** [comment]
> 

Thanks! long term we should probably create common constants so that all scripts can log using the same names. That will make looking at results more consistent.

**Pull request merged**
