### PR TITLE
Add LVIS-like Bench model

### PR DESCRIPTION
**Pull request by siboehm**
Goal: A much more manageable version of LVIS, that nevertheless captures the performance characteristics well

Bench-LVis consists of 4 layers and a mix of fully random connections, block-wise sparse connections ("convolutional") and some dense connections.

TODOs (I'd appreciate some help here):
- [ ] Is the input shape actually correct? A 4D layer should have the same input shape as a 2D layer of the same .Len()?
- [x] Fix timeout on CI

### CODE REVIEW

**Comment by siboehm** [comment]
It's timing out on CI, I'll adjust that later

**Comment by rcoreilly** [comment]
* It looks like you're not using the output of the LED env render -- that is important for generating a "realistic" input, if you want to actually learn.  This produces a 4D tensor that fits the geom of the input layer, as documented in the README in terms of the filters etc.

* Would be useful to have the layer sizes parameterized so we can test it at larger scale -- the basic objrec model size is much smaller than LVis and we want to be able to go to multiples larger of LVis.  The same pool geom can be used but just make the units per pool parameterizable.  Should give a reasonable approximation of LVis -- can test against that to see..

**Comment by siboehm** [comment]
The intent of this PR was to add a network that is easy to understand, while at the same time having performance characteristics like proper LVis, such that we can time a CUDA / Vulkan port against it. This has now been costing me more time than expected, so I'd propose we merge this and I revisit it later. 

What's currently present:
1. `bench_lvis`: This is a straightforward, easy to understand version of the `bench` network with local, random & dense connectivity patterns. Runs on random inputs, doesn't converge, has no GUI (see README for why). 
2. `bench_objrec`: This is a port of the objrec model to recent Axon. Runs on generated LED inputs, actually converges, and has a GUI. I tried stripping down the code as much as possible, but the logging code is hard to read, so I gave up on it for now.

**Review by rcoreilly — APPROVED** [review]
Ok sounds reasonable.

**Pull request merged**
