### PR TITLE
Multithread Dwt

### PR DESCRIPTION
**Pull request by siboehm**
Turn on multithreading for DWt, it was running sequentially.

We could refactor both SynCa & DWt to multithread on a per-Neuron level, would probably make things even faster.

### CODE REVIEW

**Comment by siboehm** [comment]
No idea why it was sequential. I think we just never changed it, and when I implemented the current multithreading DWt was so fast it didn't matter and I kept it sequential.

SynCa is also per Projection, so both will probably get faster (unclear by how much) if we implement more fine-grained multithreading.

**Comment by rcoreilly** [comment]
I have SynCa running per neuron in my gpu branch -- that's the difference.  I'm going to be done with that very soon so perhaps it makes sense to wait to do this PR after that?

**Comment by rcoreilly** [comment]
I've already rewritten the SynCa routines to work properly with neuron-level, and have updated tests etc..

**Comment by siboehm** [comment]
Sure. I'd have merged the current PR right now since it's only a 2 line change and makes boa a lot faster, and then we wait with per Neuron refactoring for later.

**Comment by siboehm** [comment]
Closing in favor of #156

**Comment by siboehm** [comment]
I closed this PR because I assumed that #156 was implementing the same thing, but it isn't. In #156 we multithread SynCa, here we multithread DWt. So can we merge this?

**Comment by rcoreilly** [comment]
it makes more sense to do per neuron, and update the tests, which might change slightly if the math ordering matters somehow. also probably good to merge the gpu one first and then do this after that in case there are conflicts?

**Comment by siboehm** [comment]
Math ordering will not make a difference (this function is trivially parallelizeable), so tests won't change.

**Pull request closed without merging**
