### PR TITLE
PVLV: reset urgency when VS gates

### PR DESCRIPTION
**Pull request by garymm**
In BOA, urgency is a mechanism to encourage gating by exciting the
VsMtxGo layer. It doesn't make sense to maintain the same level of
urgency once gating occurs.

Change-Id: Icb61e1d1515f5a382ec239eff2ff517c8dcf5fc5

### CODE REVIEW

**Review by rcoreilly — APPROVED** [review]
Yeah that makes sense -- good call!  Ultimately we probably want a mechanism that is sensitive to overall Drive levels -- if you're desperately hungry and fail to get food after pursuing a possible lead, then you'd want the urgency to pop back up to its previous level instead of being fully reset.. But we can iterate on that kind of thing later.

**Comment by rcoreilly** [comment]
do we want to update and merge this in time for 1.8.5?  I have a small window here where I'm online today..

**Comment by garymm** [comment]
I can merge it if / when I'm confident it helps.

**Comment by etuleu** [comment]
The results look good with this change, so I think we should merge it in and make a release. But I also had to popcode the Dist and Terrain layers.

**Pull request merged**
