### PR TITLE
Test: Parallelize GH actions

### PR DESCRIPTION
**Pull request by siboehm**
Quick test to see how much faster this'd make our CI runners.

### CODE REVIEW

**Comment by siboehm** [comment]
Lots of annoying `apt-get` timeout errors happening.

**Comment by siboehm** [comment]
@rcoreilly this runs in ~6min, vs 10min for the sequential version. If we merge this, be sure to update the required actions under

Settings -> Branches -> Branch protection Rule -> master, under `Status checks that are required`.

**Comment by siboehm** [comment]
@garymm FYI

**Review by garymm — COMMENTED** [review]
Main downside to this is that the checkout and apt-get steps are duplicated, so it uses more machine time overall. As long as we're still within the limits that GitHub provides for free, then that's not a problem.
Not sure how to check that. Maybe it's at the org (emer) level rather than repo level?

**Comment by siboehm** [comment]
It's free for public repositories, see [billing plans](https://github.com/settings/billing/plans).

**Comment by garymm** [comment]
I think it says it's free up to 2,000 minutes/month. I'm guessing we're not close to that, but would be good to check before turning this on.

**Comment by garymm** [comment]
Oh wow, good to know. OK then, no reason to not do this!

**Review by garymm — APPROVED** [review]

**Pull request merged**
