### PR TITLE
MPI-aware threading defaults

### PR DESCRIPTION
**Pull request by siboehm**

### CODE REVIEW

**Comment by siboehm** [comment]
Closes #197

**Review by rcoreilly — COMMENTED** [review]
This is only applicable for same-node mpi case.. better to not bake it in but rather set GOMAXPROCS externally based on the actual runtime configuration.

**Comment by siboehm** [comment]
That requires https://github.com/emer/empi/issues/11. I see that this PR would break LVIS MPI training .

**Comment by siboehm** [comment]
Related: https://github.com/emer/empi/issues/11

**Comment by rcoreilly** [comment]
the job submission script should know this.. Also, under SLURM used on many clusters, it automatically sets GOMAXPROCS based on actual allocated number of cores, so this calculation would be off there.

Overall, I think it is better to keep it simple in the axon code and leave this to the submission script.

**Review by etuleu — APPROVED** [review]

**Comment by etuleu** [comment]
Sorry I wasn't aware there was a conversation still going on and I just approved the PR. Please decide what you want and do it! It's confusing as hell like this!

**Pull request merged**
